<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="581" started-at="2018-01-12T09:48:18Z" finished-at="2018-01-12T09:48:19Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="581" started-at="2018-01-12T09:48:18Z" finished-at="2018-01-12T09:48:19Z">
      <class name="TestNGAssertions">
        <test-method status="PASS" signature="startReport()[pri:0, instance:TestNGAssertions@591f989e]" name="startReport" is-config="true" duration-ms="190" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="testAssert()[pri:0, instance:TestNGAssertions@591f989e]" name="testAssert" duration-ms="9" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestNGAssertions@591f989e]" name="getResult" is-config="true" duration-ms="4" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAssert status=SUCCESS method=TestNGAssertions.testAssert()[pri:0, instance:TestNGAssertions@591f989e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="testAssert1()[pri:0, instance:TestNGAssertions@591f989e]" name="testAssert1" duration-ms="4" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Babu] but found [Madhu]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Babu] but found [Madhu]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at TestNGAssertions.testAssert1(TestNGAssertions.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestNGAssertions@591f989e]" name="getResult" is-config="true" duration-ms="0" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAssert1 status=FAILURE method=TestNGAssertions.testAssert1()[pri:0, instance:TestNGAssertions@591f989e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="testAssert2()[pri:0, instance:TestNGAssertions@591f989e]" name="testAssert2" duration-ms="1" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Babu] but found [Madhu]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Babu] but found [Madhu]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at TestNGAssertions.testAssert2(TestNGAssertions.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssert2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestNGAssertions@591f989e]" name="getResult" is-config="true" duration-ms="0" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAssert2 status=FAILURE method=TestNGAssertions.testAssert2()[pri:0, instance:TestNGAssertions@591f989e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:TestNGAssertions@591f989e]" name="endReport" is-config="true" duration-ms="343" started-at="2018-01-12T15:18:18Z" finished-at="2018-01-12T15:18:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- TestNGAssertions -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
